//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 01:28:17 PM ICT 
//


package bca.dancuquocgia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaYeuCau" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaDichVu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaCanBo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoDinhDanh" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoCMND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HoVaTen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maYeuCau",
    "maDichVu",
    "maCanBo",
    "soDinhDanh",
    "soCMND",
    "hoVaTen"
})
@XmlRootElement(name = "XacThucThongTinCongDanRequest")
public class XacThucThongTinCongDanRequest {

    @XmlElement(name = "MaYeuCau", required = true)
    protected String maYeuCau;
    @XmlElement(name = "MaDichVu", required = true)
    protected String maDichVu;
    @XmlElement(name = "MaCanBo", required = true)
    protected String maCanBo;
    @XmlElement(name = "SoDinhDanh", required = true)
    protected String soDinhDanh;
    @XmlElement(name = "SoCMND", required = true)
    protected String soCMND;
    @XmlElement(name = "HoVaTen", required = true)
    protected String hoVaTen;

    /**
     * Gets the value of the maYeuCau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaYeuCau() {
        return maYeuCau;
    }

    /**
     * Sets the value of the maYeuCau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaYeuCau(String value) {
        this.maYeuCau = value;
    }

    /**
     * Gets the value of the maDichVu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaDichVu() {
        return maDichVu;
    }

    /**
     * Sets the value of the maDichVu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaDichVu(String value) {
        this.maDichVu = value;
    }

    /**
     * Gets the value of the maCanBo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaCanBo() {
        return maCanBo;
    }

    /**
     * Sets the value of the maCanBo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaCanBo(String value) {
        this.maCanBo = value;
    }

    /**
     * Gets the value of the soDinhDanh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoDinhDanh() {
        return soDinhDanh;
    }

    /**
     * Sets the value of the soDinhDanh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoDinhDanh(String value) {
        this.soDinhDanh = value;
    }

    /**
     * Gets the value of the soCMND property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoCMND() {
        return soCMND;
    }

    /**
     * Sets the value of the soCMND property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoCMND(String value) {
        this.soCMND = value;
    }

    /**
     * Gets the value of the hoVaTen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoVaTen() {
        return hoVaTen;
    }

    /**
     * Sets the value of the hoVaTen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoVaTen(String value) {
        this.hoVaTen = value;
    }

}
