//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.28 at 03:49:14 PM ICT 
//


package vn.gov.mic.dancu._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn.gov.mic.dancu._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn.gov.mic.dancu._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CongdanCollection }
     * 
     */
    public CongdanCollection createCongdanCollection() {
        return new CongdanCollection();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan }
     * 
     */
    public CongdanCollection.CongDan createCongdanCollectionCongDan() {
        return new CongdanCollection.CongDan();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan.Me }
     * 
     */
    public CongdanCollection.CongDan.Me createCongdanCollectionCongDanMe() {
        return new CongdanCollection.CongDan.Me();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan.Cha }
     * 
     */
    public CongdanCollection.CongDan.Cha createCongdanCollectionCongDanCha() {
        return new CongdanCollection.CongDan.Cha();
    }

    /**
     * Create an instance of {@link XacMinhThongTinNhanThanResponse }
     * 
     */
    public XacMinhThongTinNhanThanResponse createXacMinhThongTinNhanThanResponse() {
        return new XacMinhThongTinNhanThanResponse();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan.HoVaTen }
     * 
     */
    public CongdanCollection.CongDan.HoVaTen createCongdanCollectionCongDanHoVaTen() {
        return new CongdanCollection.CongDan.HoVaTen();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan.NgayThangNamSinh }
     * 
     */
    public CongdanCollection.CongDan.NgayThangNamSinh createCongdanCollectionCongDanNgayThangNamSinh() {
        return new CongdanCollection.CongDan.NgayThangNamSinh();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan.Me.HoVaTen }
     * 
     */
    public CongdanCollection.CongDan.Me.HoVaTen createCongdanCollectionCongDanMeHoVaTen() {
        return new CongdanCollection.CongDan.Me.HoVaTen();
    }

    /**
     * Create an instance of {@link CongdanCollection.CongDan.Cha.HoVaTen }
     * 
     */
    public CongdanCollection.CongDan.Cha.HoVaTen createCongdanCollectionCongDanChaHoVaTen() {
        return new CongdanCollection.CongDan.Cha.HoVaTen();
    }

}
