//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 08:21:03 AM ICT 
//


package com.anhnbt.lgsp.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaYeuCau" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaDVC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaTichHop" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaDonVi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaCanBo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoDinhDanh" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoCMND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HoVaTen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NgayThangNamSinh" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maYeuCau",
    "maDVC",
    "maTichHop",
    "maDonVi",
    "maCanBo",
    "soDinhDanh",
    "soCMND",
    "hoVaTen",
    "ngayThangNamSinh"
})
@XmlRootElement(name = "XacMinhThongTinNhanThanRequest")
public class XacMinhThongTinNhanThanRequest {

    @XmlElement(name = "MaYeuCau", required = true)
    protected String maYeuCau;
    @XmlElement(name = "MaDVC", required = true)
    protected String maDVC;
    @XmlElement(name = "MaTichHop", required = true)
    protected String maTichHop;
    @XmlElement(name = "MaDonVi", required = true)
    protected String maDonVi;
    @XmlElement(name = "MaCanBo", required = true)
    protected String maCanBo;
    @XmlElement(name = "SoDinhDanh", required = true)
    protected String soDinhDanh;
    @XmlElement(name = "SoCMND", required = true)
    protected String soCMND;
    @XmlElement(name = "HoVaTen", required = true)
    protected String hoVaTen;
    @XmlElement(name = "NgayThangNamSinh", required = true)
    protected String ngayThangNamSinh;

    /**
     * Gets the value of the maYeuCau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaYeuCau() {
        return maYeuCau;
    }

    /**
     * Sets the value of the maYeuCau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaYeuCau(String value) {
        this.maYeuCau = value;
    }

    /**
     * Gets the value of the maDVC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaDVC() {
        return maDVC;
    }

    /**
     * Sets the value of the maDVC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaDVC(String value) {
        this.maDVC = value;
    }

    /**
     * Gets the value of the maTichHop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaTichHop() {
        return maTichHop;
    }

    /**
     * Sets the value of the maTichHop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaTichHop(String value) {
        this.maTichHop = value;
    }

    /**
     * Gets the value of the maDonVi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaDonVi() {
        return maDonVi;
    }

    /**
     * Sets the value of the maDonVi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaDonVi(String value) {
        this.maDonVi = value;
    }

    /**
     * Gets the value of the maCanBo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaCanBo() {
        return maCanBo;
    }

    /**
     * Sets the value of the maCanBo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaCanBo(String value) {
        this.maCanBo = value;
    }

    /**
     * Gets the value of the soDinhDanh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoDinhDanh() {
        return soDinhDanh;
    }

    /**
     * Sets the value of the soDinhDanh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoDinhDanh(String value) {
        this.soDinhDanh = value;
    }

    /**
     * Gets the value of the soCMND property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoCMND() {
        return soCMND;
    }

    /**
     * Sets the value of the soCMND property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoCMND(String value) {
        this.soCMND = value;
    }

    /**
     * Gets the value of the hoVaTen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoVaTen() {
        return hoVaTen;
    }

    /**
     * Sets the value of the hoVaTen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoVaTen(String value) {
        this.hoVaTen = value;
    }

    /**
     * Gets the value of the ngayThangNamSinh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgayThangNamSinh() {
        return ngayThangNamSinh;
    }

    /**
     * Sets the value of the ngayThangNamSinh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgayThangNamSinh(String value) {
        this.ngayThangNamSinh = value;
    }

}
