//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.28 at 03:49:14 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gtel.vn/qldc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vn.gtel.qldc;
